{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cache_aware_router.fullname" . }}
  labels: {{- include "cache_aware_router.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "cache_aware_router.selectorLabels" . | nindent 6 }}
{{- end }}
