{{- if .Values.ha.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cache_aware_router.fullname" . }}
  labels: {{- include "cache_aware_router.labels" . | nindent 4 }}
{{- end }}
